;; NOTE: emacs.scm is generated from Emacs.org. Please edit that file
;;        in Emacs and emacs.scm will be generated automatially

(specifications->manifest
 (list "emacs-native-comp"
       "emacs-guix"
       "emacs-use-package"
       "emacs-evil"
       "emacs-evil-collection"
       "emacs-which-key"
       "emacs-general"
       "emacs-swiper"
       "emacs-org"
       "emacs-org-bullets"
       "emacs-visual-fill-column"
       "emacs-org-roam"
       "emacs-markdown-mode"
       "emacs-vertico"
       "emacs-orderless"
       "emacs-selectrum"
       "emacs-consult"
       "emacs-embark"
       "emacs-marginalia"
       "emacs-ivy"
       "emacs-counsel"
       "emacs-ivy-rich"
       "emacs-projectile"
       "emacs-counsel-projectile"
       "emacs-magit"
       "emacs-pass"
       "pinentry"
       "password-store"
       "emacs-pinentry"
       "emacs-helpful"
       "emacs-doom-themes"
       "emacs-all-the-icons"
       "emacs-doom-modeline"
       "emacs-rainbow-delimiters"
       "emacs-exwm"
       "emacs-desktop-environment"
       ))
