(specifications->manifest
   (list "glibc-locales"
         "font-abattis-cantarell"
         "font-fira-code"
         "xrandr"
         "zsh"
         "xmodmap"
         "htop"
         "fontconfig"
         "neovim"
         "dunst"
         "picom"
         "xclip"
         "xwallpaper"
         "sxiv"
         "alacritty" 
         "firefox"
         "lf"
         "mpv"
         "mpd"
         "qutebrowser" ))
