# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line istead of two
[line_break]
disabled = true

# Enable hostname Module
[hostname]
ssh_only = false
format = "[$hostname](blue) "
disabled = false

# Username Config
[username]
style_user = "blue"
style_root = "red"
format = "[$user]($style)@"
disabled = false
show_always = true

# Replace the "❯" symbol in the prompt with "➜"
[character] 
success_symbol = "[❯](bold red)[❯](bold yellow)[❯](bold green)"

[rust]
disabled = true
